"""phase2_all_models

Revision ID: 4589973d8b1f
Revises: 
Create Date: 2026-05-21 16:28:43.926740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import models


# revision identifiers, used by Alembic.
revision: str = '4589973d8b1f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', models.PortableUUID(length=36), nullable=False),
    sa.Column('mrn', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('cnic', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('emergency_contact', models.PortableJSONB(), nullable=True),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('chronic_conditions', sa.Text(), nullable=True),
    sa.Column('medical_history', models.PortableJSONB(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_full_name'), 'patients', ['full_name'], unique=False)
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_index(op.f('ix_patients_mrn'), 'patients', ['mrn'], unique=True)
    op.create_index(op.f('ix_patients_phone'), 'patients', ['phone'], unique=False)
    op.create_table('services',
    sa.Column('id', models.PortableUUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('ASSESSMENT', 'THERAPY', 'PROCEDURE', 'PACKAGE', name='servicecategory'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', models.PortableUUID(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'DOCTOR', 'INTERN', 'RECEPTIONIST', name='userrole'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', models.PortableUUID(length=36), nullable=False),
    sa.Column('patient_id', models.PortableUUID(length=36), nullable=False),
    sa.Column('doctor_id', models.PortableUUID(length=36), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('INITIAL_ASSESSMENT', 'FOLLOW_UP', 'REHAB_SESSION', name='appointmenttype'), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='appointmentstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('session_num', sa.Integer(), nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_scheduled_at'), 'appointments', ['scheduled_at'], unique=False)
    op.create_table('doctor_availability',
    sa.Column('id', models.PortableUUID(length=36), nullable=False),
    sa.Column('doctor_id', models.PortableUUID(length=36), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_availability_doctor_id'), 'doctor_availability', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_availability_id'), 'doctor_availability', ['id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', models.PortableUUID(length=36), nullable=False),
    sa.Column('patient_id', models.PortableUUID(length=36), nullable=False),
    sa.Column('doctor_id', models.PortableUUID(length=36), nullable=False),
    sa.Column('medications', models.PortableJSONB(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('is_refillable', sa.Boolean(), nullable=False),
    sa.Column('pdf_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_doctor_id'), 'prescriptions', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_id'), 'prescriptions', ['id'], unique=False)
    op.create_index(op.f('ix_prescriptions_patient_id'), 'prescriptions', ['patient_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', models.PortableUUID(length=36), nullable=False),
    sa.Column('user_id', models.PortableUUID(length=36), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('treatment_plans',
    sa.Column('id', models.PortableUUID(length=36), nullable=False),
    sa.Column('patient_id', models.PortableUUID(length=36), nullable=False),
    sa.Column('doctor_id', models.PortableUUID(length=36), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('goals', models.PortableJSONB(), nullable=True),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('frequency_per_week', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'PAUSED', name='treatmentplanstatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_plans_doctor_id'), 'treatment_plans', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_treatment_plans_id'), 'treatment_plans', ['id'], unique=False)
    op.create_index(op.f('ix_treatment_plans_patient_id'), 'treatment_plans', ['patient_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', models.PortableUUID(length=36), nullable=False),
    sa.Column('patient_id', models.PortableUUID(length=36), nullable=False),
    sa.Column('appointment_id', models.PortableUUID(length=36), nullable=True),
    sa.Column('invoice_number', sa.String(length=30), nullable=False),
    sa.Column('line_items', models.PortableJSONB(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PARTIAL', 'PAID', 'CANCELLED', 'OVERDUE', name='invoicestatus'), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_patient_id'), 'invoices', ['patient_id'], unique=False)
    op.create_table('medical_records',
    sa.Column('id', models.PortableUUID(length=36), nullable=False),
    sa.Column('patient_id', models.PortableUUID(length=36), nullable=False),
    sa.Column('appointment_id', models.PortableUUID(length=36), nullable=True),
    sa.Column('doctor_id', models.PortableUUID(length=36), nullable=False),
    sa.Column('vitals', models.PortableJSONB(), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('subjective', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('assessment', sa.Text(), nullable=True),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('diagnosis_codes', models.PortableJSONB(), nullable=True),
    sa.Column('physio_assessment', models.PortableJSONB(), nullable=True),
    sa.Column('is_finalized', sa.Boolean(), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_records_doctor_id'), 'medical_records', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_medical_records_id'), 'medical_records', ['id'], unique=False)
    op.create_index(op.f('ix_medical_records_patient_id'), 'medical_records', ['patient_id'], unique=False)
    op.create_table('outcome_measures',
    sa.Column('id', models.PortableUUID(length=36), nullable=False),
    sa.Column('patient_id', models.PortableUUID(length=36), nullable=False),
    sa.Column('doctor_id', models.PortableUUID(length=36), nullable=False),
    sa.Column('appointment_id', models.PortableUUID(length=36), nullable=True),
    sa.Column('measure_type', sa.Enum('VAS', 'KOOS', 'NDI', 'DASH', 'ODI', 'PSFS', 'CUSTOM', name='outcomemeasuretype'), nullable=False),
    sa.Column('responses', models.PortableJSONB(), nullable=True),
    sa.Column('total_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outcome_measures_doctor_id'), 'outcome_measures', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_outcome_measures_id'), 'outcome_measures', ['id'], unique=False)
    op.create_index(op.f('ix_outcome_measures_patient_id'), 'outcome_measures', ['patient_id'], unique=False)
    op.create_table('session_progress',
    sa.Column('id', models.PortableUUID(length=36), nullable=False),
    sa.Column('plan_id', models.PortableUUID(length=36), nullable=False),
    sa.Column('appointment_id', models.PortableUUID(length=36), nullable=True),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('exercises_completed', models.PortableJSONB(), nullable=True),
    sa.Column('pain_before', sa.Integer(), nullable=True),
    sa.Column('pain_after', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('therapist_id', models.PortableUUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['treatment_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['therapist_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_progress_id'), 'session_progress', ['id'], unique=False)
    op.create_index(op.f('ix_session_progress_plan_id'), 'session_progress', ['plan_id'], unique=False)
    op.create_index(op.f('ix_session_progress_therapist_id'), 'session_progress', ['therapist_id'], unique=False)
    op.create_table('treatment_milestones',
    sa.Column('id', models.PortableUUID(length=36), nullable=False),
    sa.Column('plan_id', models.PortableUUID(length=36), nullable=False),
    sa.Column('milestone_name', sa.String(length=255), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('achieved_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['treatment_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_milestones_id'), 'treatment_milestones', ['id'], unique=False)
    op.create_index(op.f('ix_treatment_milestones_plan_id'), 'treatment_milestones', ['plan_id'], unique=False)
    op.create_table('treatment_plan_exercises',
    sa.Column('id', models.PortableUUID(length=36), nullable=False),
    sa.Column('plan_id', models.PortableUUID(length=36), nullable=False),
    sa.Column('exercise_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('resistance_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('frequency', sa.String(length=100), nullable=True),
    sa.Column('video_url', sa.String(length=512), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['treatment_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_plan_exercises_id'), 'treatment_plan_exercises', ['id'], unique=False)
    op.create_index(op.f('ix_treatment_plan_exercises_plan_id'), 'treatment_plan_exercises', ['plan_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', models.PortableUUID(length=36), nullable=False),
    sa.Column('invoice_id', models.PortableUUID(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('method', sa.Enum('CASH', 'CARD', 'TRANSFER', 'E_WALLET', name='paymentmethod'), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('payment_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_treatment_plan_exercises_plan_id'), table_name='treatment_plan_exercises')
    op.drop_index(op.f('ix_treatment_plan_exercises_id'), table_name='treatment_plan_exercises')
    op.drop_table('treatment_plan_exercises')
    op.drop_index(op.f('ix_treatment_milestones_plan_id'), table_name='treatment_milestones')
    op.drop_index(op.f('ix_treatment_milestones_id'), table_name='treatment_milestones')
    op.drop_table('treatment_milestones')
    op.drop_index(op.f('ix_session_progress_therapist_id'), table_name='session_progress')
    op.drop_index(op.f('ix_session_progress_plan_id'), table_name='session_progress')
    op.drop_index(op.f('ix_session_progress_id'), table_name='session_progress')
    op.drop_table('session_progress')
    op.drop_index(op.f('ix_outcome_measures_patient_id'), table_name='outcome_measures')
    op.drop_index(op.f('ix_outcome_measures_id'), table_name='outcome_measures')
    op.drop_index(op.f('ix_outcome_measures_doctor_id'), table_name='outcome_measures')
    op.drop_table('outcome_measures')
    op.drop_index(op.f('ix_medical_records_patient_id'), table_name='medical_records')
    op.drop_index(op.f('ix_medical_records_id'), table_name='medical_records')
    op.drop_index(op.f('ix_medical_records_doctor_id'), table_name='medical_records')
    op.drop_table('medical_records')
    op.drop_index(op.f('ix_invoices_patient_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_treatment_plans_patient_id'), table_name='treatment_plans')
    op.drop_index(op.f('ix_treatment_plans_id'), table_name='treatment_plans')
    op.drop_index(op.f('ix_treatment_plans_doctor_id'), table_name='treatment_plans')
    op.drop_table('treatment_plans')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_prescriptions_patient_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_doctor_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_doctor_availability_id'), table_name='doctor_availability')
    op.drop_index(op.f('ix_doctor_availability_doctor_id'), table_name='doctor_availability')
    op.drop_table('doctor_availability')
    op.drop_index(op.f('ix_appointments_scheduled_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_patients_phone'), table_name='patients')
    op.drop_index(op.f('ix_patients_mrn'), table_name='patients')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_full_name'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
